services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  redis:
    image: redis:latest
