apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reflex-app
spec:
  template:
    spec:
      containers:
      # Backend container
      - name: backend
        image: gcr.io/axiomatic-path-440205-v4/backend
        env:
        - name: REDIS_URL
          value: "redis://localhost:6379"
        - name: PYTHONUNBUFFERED
          value: "1"

      # Frontend container (nginx)
      - name: frontend
        image: gcr.io/axiomatic-path-440205-v4/frontend
        ports:
        - containerPort: 8080

      # Redis container
      - name: redis
        image: redis:latest
